### ISSUE TITLE
[FEAT] 은주님 노션 글 참고하며 git flow 샘플 만들어 보는 중 ...

### ISSUE THREAD

**Issue by cchanmi** [30th-THE-SOPT-iOS-Part/HwangChanMi#1]
## 🍎 이슈 요약

은주님 노션에 git flow 정리글 정말 최고예요......!!! 👍

## ✅ 체크 리스트

- 은주님 찬양하기

**Comment by jane1choi** [comment]
호거거걱 누가 좌표찍어줘서 달려왔습니다...이게 모야 선배야..나 쩜 감동쓰..
도움 필요한 것이 있다면 언제든지 연락갈겨주세요😆🥰

**Comment by cchanmi** [comment]
너무 든든하군요... 🥳
